export const SUBJECT_RECIPES = [
  {
    name: "Siêu Tốc",
    requiredFlags: ["Sức mạnh", "Nhanh nhẹn", "Khéo léo"],
    icon: require("../../abilities/SubjectIcons/Sieutoc.webp"),
    passive: {
      name: "Siêu tốc",
      skillCategory: "passive",
      description: "+50% tốc độ tăng thanh tấn công",
      trigger: { type: "onTurnStart", chance: 100 },
      effect: {
        type: "buff",
        target: "self",
        stat: "agiPercent",
        value: 50,
        stackable: false,
        duration: 5,
      },
    },
  },
  {
    name: "Chính Xác",
    requiredFlags: ["Trí lực", "Uy tín", "Khéo léo"],
    icon: require("../../abilities/SubjectIcons/Chinhxac.webp"),
    passive: {
      name: "Chính xác",
      skillCategory: "passive",
      description: "Tăng 20% độ chính xác.",
      trigger: { type: "onTurnStart", chance: 100 },
      effect: {
        type: "buff",
        target: "self",
        stat: "accuracy",
        value: 20,
        stackable: false,
        duration: 5,
      },
    },
  },
  {
    name: "Bạo Kích",
    requiredFlags: ["Trí lực", "Bền bỉ", "Uy tín"],
    icon: require("../../abilities/SubjectIcons/Baokich.webp"),
    passive: {
      name: "Bạo kích",
      skillCategory: "passive",
      description: "Tăng 20% tỷ lệ Bạo kích",
      trigger: { type: "onTurnStart", chance: 100 },
      effect: {
        type: "buff",
        target: "self",
        stat: "critRate",
        value: 20,
        stackable: false,
        duration: 5,
      },
    },
  },
  {
    name: "Uyển chuyển",
    requiredFlags: ["Trí lực", "May mắn", "Uy tín"],
    icon: require("../../abilities/SubjectIcons/Uyenchuyen.webp"),
    passive: {
      name: "Uyển chuyển",
      skillCategory: "passive",
      description: "Tăng 20% né tránh",
      trigger: { type: "onTurnStart", chance: 100 },
      effect: {
        type: "buff",
        target: "self",
        stat: "evasion",
        value: 20,
        stackable: false,
        duration: 5,
      },
    },
  },
  {
    name: "Bùng Nổ",
    requiredFlags: ["May mắn", "Khéo léo", "Sức mạnh"],
    icon: require("../../abilities/SubjectIcons/Bungno.webp"),
    passive: {
      name: "Bùng nổ",
      skillCategory: "passive",
      description: "Tăng 40% sát thương chí mạng",
      trigger: { type: "onTurnStart", chance: 100 },
      effect: {
        type: "buff",
        target: "self",
        stat: "critDamage",
        stackable: false,
        value: 40,
        duration: 5,
      },
    },
  },
  {
    name: "Cường Hóa",
    requiredFlags: ["Khéo léo", "May mắn", "Bền bỉ"],
    icon: require("../../abilities/SubjectIcons/Thuctai2.webp"),
    passive: {
      name: "Cường hóa",
      skillCategory: "passive",
      description: "Tăng 20% skill amp Sát thương.",
      trigger: { type: "onTurnStart", chance: 100 },
      effect: {
        type: "buff",
        target: "self",
        stat: "skillAmp",
        value: 20,
        stackable: false,
        duration: 5,
      },
    },
  },
  {
    name: "Trưởng thành",
    requiredFlags: ["Bền bỉ", "Uy tín", "Sức mạnh"],
    icon: require("../../abilities/SubjectIcons/Truongthanh.webp"),
    passive: {
      name: "Trưởng thành",
      skillCategory: "passive",
      description: "Tăng 20% Def.",
      trigger: { type: "onTurnStart", chance: 100 },
      effect: {
        type: "buff",
        target: "self",
        stat: "defend",
        value: 20,
        stackable: false,
        duration: 5,
      },
    },
  },
];
